---
detectors:
  NestedIterators:
    enabled: true
    exclude: []
    max_allowed_nesting: 3
    ignore_iterators:
      - tap
  DuplicateMethodCall:
    max_calls: 2
  TooManyStatements:
    enabled: true
    exclude:
      - initialize
    max_statements: 10
  RepeatedConditional:
    max_ifs: 3
  IrresponsibleModule:
    enabled: false

exclude_paths:
  - 'db/migrate'
  - 'node_modules'
  - 'cache'
  - 'vendor'

directories:
  'config':
    IrresponsibleModule:
      enabled: false
  'app/controllers':
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    InstanceVariableAssumption:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
  'app/models':
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  'app/services':
    UncommunicativeVariableName:
      enabled: false
    TooManyInstanceVariables:
      enabled: false
  'app/jobs':
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  'app/helpers':
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  'spec/support':
    UtilityFunction:
      enabled: false
    IrresponsibleModule:
      enabled: false
    LongParameterList:
      enabled: false
    DataClump:
      enabled: false
    ManualDispatch:
      enabled: false
    FeatureEnvy:
      enabled: false
